controllers:
    # On importe automatiquement les routes définies grâce aux attributs
    # #[Route(...)] présents sur les méthodes des contrôleurs.
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
